name: Build mutuelle service

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build du programme
        run: go build -o roc-service
